# Generated by Django 2.0 on 2018-01-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_auto_20180130_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='manufacturing_country_id',
            new_name='manufacturing_country',
        ),
    ]
